"""Generate deliverables/btc_accumulation_model.ipynb, the educational notebook, complete in
structure and prose per the Stacking Sats educational notebook outline (executive summary,
visual EDA highlights, model explanation, with links to the supporting notebooks). Every
number is read from the committed artefacts; the final adjudication section reports the
registered reading's status and fills itself from output/final_reading.json once that reading
has happened. Supersedes the draft outline previously generated by build_notebooks_part2.py.

Run from the repository root:  python tools/build_edu_notebook.py
"""
import os
import sys

import nbformat as nbf

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
sys.path.insert(0, "tools")
from nbcommon import PATHFIX  # noqa: E402

cells = []
md = lambda s: cells.append(nbf.v4.new_markdown_cell(s))
code = lambda s: cells.append(nbf.v4.new_code_cell(s))

md("# Bitcoin Accumulation via Usage Momentum and Budget Pacing")

md("## 1. Executive summary\n\n"
   "Uniform dollar cost averaging buys the same amount of Bitcoin every day. This study asks "
   "whether a rule that varies the daily amount, using only information available at the "
   "time, accumulates more satoshis per dollar over rolling 12-month windows, judged by the "
   "Trilemma Foundation's published scoring framework (Final Model Score = 0.5 x win rate + "
   "0.5 x recency-weighted percentile of satoshis per dollar).\n\n"
   "**The approach.** The model forecasts the 90-day forward return with a small "
   "gradient-boosted learner trained on three signals the data itself ranked first: hash-rate "
   "momentum, transaction-fee momentum, and position in the halving calendar. Training is "
   "purged walk-forward (a model refit every 90 days sees only samples whose outcome had "
   "fully closed), the forecast is standardised against its own past only, and a "
   "remaining-budget pacing allocator turns it into daily weights that satisfy the "
   "tournament's constraints by construction: every weight above the minimum, every window "
   "summing to one, no forward information anywhere. The tournament's own leakage probe, "
   "which masks the future and demands unchanged weights, passes 51 of 51 dates on every "
   "reported model.\n\n"
   "**The evidence.** The stable representative of the final model family beat uniform DCA "
   "in 85.7 per cent of the 2,791 live rolling windows, and its three-configuration mean "
   "Final Model Score of 65.50 sits above the 2025 tournament reference implementation's "
   "62.91 on identical data. Selection ran as twelve pre-registered rounds with six negative "
   "results kept on the record, and the final choice among the three frozen finalists is "
   "made by a one-time reading of sequestered windows under a rule registered before any of "
   "those windows completed (section 5).\n\n"
   "**Strengths and limitations.** The model's edge is concentrated where usage signals "
   "lead price; it won every window starting in 2018 and 2021 to 2023, and its weakness is "
   "the 2024 to 2026 drawdown era, which is reported, not hidden. The study's most "
   "instructive result is negative: three successive refinement generations improved the "
   "development metric while out-of-development performance fell monotonically, a measured "
   "demonstration of selection-metric overfitting that the pre-registration protocol caught "
   "(section 4).")
code(PATHFIX)

md("## 2. What the data shows\n\n"
   "The exploratory findings that shaped the model, one chart each; the full analysis is in "
   "[notebook 02](../notebooks/02_eda.ipynb) and the numbered findings in "
   "[docs/EDA_FINDINGS.md](../docs/EDA_FINDINGS.md).\n\n"
   "**Price is a sequence of halving-anchored cycles**, with deep drawdowns in each cycle's "
   "second half; a daily accumulation rule lives inside these swings.\n\n"
   "![price](../output/eda/01_price_log.png)\n\n"
   "**Uniform DCA is a weak percentile performer inside its own windows**: its mean "
   "sats-per-dollar percentile over the live windows is 38.6, because equal daily buying "
   "overweights the expensive stretches of trending windows. This gap is the opportunity.\n\n"
   "![uniform](../output/eda/04_uniform_percentile.png)\n\n"
   "**Usage signals out-rank valuation and price momentum** for the forward 12-month "
   "outcome: hash-rate momentum (rank correlation 0.49), halving-cycle position (0.48) and "
   "fee momentum (0.40) lead the registered importance table, while the 200-day "
   "moving-average gap is close to noise (0.0005). The model is built on the top three.\n\n"
   "![features](../output/eda/06_feature_distributions.png)")

md("## 3. How the model works, and why it beats uniform DCA\n\n"
   "**Features.** Three inputs, each computable on the day it is used: the ratio of 30-day "
   "to 365-day average hash rate, the same ratio for total transaction fees, and the cosine "
   "position within the 4-year halving cycle. All are lagged one day, so the weight for day "
   "t is fixed at the close of day t-1.\n\n"
   "**Decision mechanism.** A HistGradientBoosting regressor, refit every 90 days on an "
   "expanding window of fully closed labels, forecasts the 90-day forward log return. The "
   "forecast is standardised against the expanding mean and deviation of its own past "
   "values, clipped, and mapped to a bounded daily multiplier; the asymmetric variants tilt "
   "harder into buy signals than caution signals. The pacing allocator spends the even pace "
   "of the remaining budget scaled by that multiplier, so constraint satisfaction is "
   "structural, not corrected after the fact.\n\n"
   "**Why it wins.** Usage momentum leads price at the quarterly horizon in this data, and "
   "the recency-weighted metric rewards conviction: raising the multiplier ceiling from 5 to "
   "12 was the single largest scoring improvement in the study. Blends, wider feature sets, "
   "alternative learners, sentiment data and learned modulators were all tested in "
   "registered rounds and all lost to this simple engine; the full record, losers included, "
   "is in [notebook 08](../notebooks/08_feature_ml_ranking.ipynb), "
   "[notebook 09](../notebooks/09_rounds6to9.ipynb) and "
   "[notebook 10](../notebooks/10_rounds10to12.ipynb).\n\n"
   "**Why it should generalise.** Causality is enforced, not assumed: the tournament's "
   "forward-leakage probe retrains the whole pipeline under masked data at 51 dates and "
   "requires identical weights. Selection used an early development period separated from "
   "later data by a 12-month embargo, robustness was measured (no single pre-2024 year "
   "carries the result; the stable finalists move under one point when any parameter is "
   "perturbed alone), and every learner number is reported under two library versions.")
code("import json\nimport pandas as pd\n"
     "ranking = pd.read_csv('output/model_ranking.csv', index_col=0)\n"
     "ranking.round(2)")
code("loyo = pd.read_csv('output/loyo_finalists.csv')\n"
     "print('leave-one-year-of-starts-out win rates (regime B):')\n"
     "loyo.pivot(index='excluded_year', columns='model', values='win_rate').round(2)")

md("## 4. The honest finding: a selection metric caught overfitting\n\n"
   "Rounds 6, 11 and 12 each improved the development selection metric: 73.12, then 73.41, "
   "then 74.80. The untouched hold-out fell in lockstep: 57.38, then 52.12, then 34.14. "
   "Every point gained on the metric that chose the models was paid for on the data that "
   "did not, the ordering inverts on every out-of-development measure, and the pattern "
   "replicates exactly under the pinned tournament environment. The refinement line was "
   "terminated on this evidence. Most studies that overfit never find out; this one "
   "measured it, because every round was registered before it ran and every reading was "
   "recorded.\n\n"
   "![gradient](../output/10_dev_gradient.png)")

md("## 5. The final model, by a rule fixed before the data existed\n\n"
   "Because the development metric and the hold-out point at different finalists, the "
   "adjudication was registered before the first sequestered window completed: the final "
   "model is whichever of the three frozen finalists scores highest on the windows starting "
   "from September 2025, read exactly once on or after 15 October 2026, ties breaking "
   "toward the earlier candidate. That reading doubles as the study's final out-of-sample "
   "table. The cell below reports the reading's status and fills itself when it has "
   "happened.")
code("import os\nfrom model.final_reading import OUT, READING_OPENS, FINALISTS\n"
     "if os.path.exists(OUT):\n"
     "    fr = json.load(open(OUT))\n"
     "    print('FINAL MODEL:', fr['final_model'])\n"
     "    print('sequestered score', round(fr['final_score_sequestered'], 2),\n"
     "          '| read on', fr['read_on'], '| windows',\n"
     "          int(fr['candidates'][fr['final_model']]['windows']))\n"
     "else:\n"
     "    print('The registered reading opens on', READING_OPENS, 'and has not yet happened;')\n"
     "    print('the sequestered windows remain untouched. Finalists:')\n"
     "    for f in FINALISTS:\n"
     "        print('  -', f)")

md("## 6. The tournament-format artefact\n\n"
   "The 2025 tournament's strict 3-cell submission format forbids new import statements, "
   "which keeps the learner out of that artefact; the 3-cell notebook therefore carries the "
   "study's strongest format-compliant simple model, a numpy-and-pandas rule that passes "
   "the tournament's own checks on the frozen tournament dataset "
   "([tournament_2025/btc_accumulation_model.ipynb](../tournament_2025/btc_accumulation_model.ipynb), "
   "boilerplate hash-verified), while the learner family above is the study's primary "
   "result where no format restriction exists.\n\n"
   "## 7. Limitations and future work\n\n"
   "Single asset, no spreads or slippage (outside the tournament's scope), roughly one and "
   "a half halving cycles of effective training data behind the calendar feature, and a "
   "recency-weighted metric that ties any score to the current market phase. Future work, "
   "in order of expected value: prediction-market signals (Polymarket) as features, live "
   "on-chain feeds beyond the community series, and convex combinations of valid models, "
   "which inherit validity by construction.")

n = nbf.v4.new_notebook()
n.cells = cells
n.metadata["kernelspec"] = {"name": "python3", "display_name": "Python 3", "language": "python"}
nbf.write(n, "deliverables/btc_accumulation_model.ipynb")
print("written deliverables/btc_accumulation_model.ipynb")
